<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width">
	<title>Links</title>
	<link rel="icon" href="favicon.ico" type="image/x-icon">
	<style type="text/css">
body {
	font-size: 12px;
	font-family: Arial, Tahome, sans-serif;
}

a {
	white-space: nowrap;
	overflow: hidden;
	width: 72px;
	text-overflow: ellipsis;
	display: block;
	text-decoration: none !important;
	color: black;
}

.e {
	width: 72px;
	height: 86px;
	margin: 4px 6px;
	float: left;
	text-align: center;
}

.m {
	margin: 0 auto;
}
	</style>
</head>
<body><div class="m">@@LINKS@@</div></body>
</html>
